# syntax=docker/dockerfile:1.6
ARG ROS_DISTRO=jazzy
FROM ros:${ROS_DISTRO}-ros-base

# Base tools + ROS2 Python tooling and common packages
# Options are needed to build locally
RUN apt-get -o Acquire::http::Pipeline-Depth="0" \
            -o Acquire::http::No-Cache=true \
            -o Acquire::BrokenProxy=true \
    update && \
    apt-get -o Acquire::http::Pipeline-Depth="0" \
            -o Acquire::http::No-Cache=true \
            -o Acquire::BrokenProxy=true \
    install -y --no-install-recommends \
      python3-pip python3-colcon-common-extensions \
      python3.12-venv \
      ros-${ROS_DISTRO}-rosbag2-storage-mcap \
      ros-${ROS_DISTRO}-rmw-cyclonedds-cpp \
      ros-${ROS_DISTRO}-rclpy ros-${ROS_DISTRO}-ros2bag \
      git curl nano && \
    rm -rf /var/lib/apt/lists/*

COPY requirements.txt requirements.txt
RUN pip3 install --no-cache-dir -r requirements.txt

COPY docker/cyclonedds.xml /etc/cyclonedds.xml
ENV CYCLONEDDS_URI=file:///etc/cyclonedds.xml

# Workspace path
ENV WS=/ws
RUN mkdir -p ${WS}/src
WORKDIR ${WS}

# Adds python paths
RUN python3 -c "import site, pathlib; p=pathlib.Path(site.getsitepackages()[0])/'ros2.pth'; \
p.write_text('/opt/ros/jazzy/lib/python3.12/site-packages\n/opt/ros/jazzy/local/lib/python3.12/dist-packages\n')"

# Entrypoint will source ROS and the workspace, then exec your command
COPY scripts/entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]
CMD ["/bin/bash"]
